<a href="https://colab.research.google.com/github/AdicherlaVenkataSai/GooglecrashML/blob/master/1.%20NumPy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
'''
NumPy is a Python library for creating and manipulating 
vectors and matrices
'''

import numpy as np

In [0]:
'''
np.array is to create a NumPy matix (1/2d..)
'''
one_D_array = np.array([1,2,3,4,5])
print(one_D_array)

two_D_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(two_D_array)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [0]:
'''
to populate matrix with all zeros call np.zeros, all ones np.ones
'''
m = np.ones([])
m

array(1.)

In [0]:
'''
array with sequence of numbers 
'''
seq = np.arange(5,12) # excluding 12
seq

array([ 5,  6,  7,  8,  9, 10, 11])

In [0]:
'''
populate matrices with random numbers acoss certain ranges 

we'll get random numbers array of size = size
'''
ran = np.random.randint(low = 1, high = 100, size = (5))
ran

array([71, 56, 13, 39, 40])

In [0]:
# floating point values

ran_f = np.random.random([5])
ran_f

array([0.75903844, 0.69575902, 0.12979606, 0.8810911 , 0.63877664])

## Mathematical Operations on NumPy Operands

If you want to add or subtract two vectors or matrices, linear algebra requires that the two operands have the same dimensions. Furthermore, if you want to multiply two vectors or matrices, linear algebra imposes strict rules on the dimensional compatibility of operands. Fortunately, NumPy uses a trick called [**broadcasting**](https://developers.google.com/machine-learning/glossary/#broadcasting) to virtually expand the smaller operand to dimensions compatible for linear algebra. For example, the following operation uses broadcasting to add 2.0 to the value of every item in the vector created in the previous code cell:

In [0]:
ran_ = ran_f + 2.0 
ran_

array([2.75903844, 2.69575902, 2.12979606, 2.8810911 , 2.63877664])

In [0]:
# broadcasting to multiply

ran__ = ran * 3
ran__

array([213, 168,  39, 117, 120])

## Task 1: Create a Linear Dataset

Your goal is to create a simple dataset consisting of a single feature and a label as follows:

1. Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named `feature`.
2. Assign 15 values to a NumPy array named `label` such that:

```
   label = (3)(feature) + 4
```
For example, the first value for `label` should be:

```
  label = (3)(6) + 4 = 22
 ```

_______________________________________

mine:
```
feature = np.arange(6, 21) # write your code here
print(feature)
label = []   # write your code here
for i in range(len(feature)):
  label1 = (3*feature[i]) + 4
  label.append(label1)

print(label)
```

sol:

```
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)
```

## Task 2: Add Some Noise to the Dataset

To make your dataset a little more realistic, insert a little random noise into each element of the `label` array you already created. To be more precise, modify each value assigned to `label` by adding a *different* random floating-point value between -2 and +2. 

Don't rely on broadcasting. Instead, create a `noise` array having the same dimension as `label`.


______________________________________

as we used the label var in previous task, we got to know  it has 15 elts in it, noise to be produced btw -2 and +2 and we need floating point values (np.random.random([x])). To produce floating point values we can provide only 1 argument, which is non negative
for accquire the range btw - 2 and +2 we have code as below


mine:
```
noise = np.random.random(15)*4 -2  # write your code here
print(noise)
label += noise     # write your code here
print(label)
```

sol:
```
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)
```