# Day 14. Numpy and Pandas

In [1]:
import numpy

In [8]:
# creating an numpy array
a = numpy.array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [11]:
# creating a list(lists can perform the column operations)
b = [11, 12, 13]

In [12]:
type(b)

list

In [13]:
# inorder avoid the limitation of "no column operations" in list we're converting it into numpy array using `asarray()` function.
b = numpy.asarray(b)

In [14]:
type(b)

numpy.ndarray

In [15]:
a.shape, b.shape

((3,), (3,))

In [16]:
a, b

(array([1, 2, 3]), array([11, 12, 13]))

In [61]:
# 2d array
a = numpy.array([[1, "sai", 10], [2, "sia", 20], [3, "ias" ,30]])
a, type(a), a.shape

(array([['1', 'sai', '10'],
        ['2', 'sia', '20'],
        ['3', 'ias', '30']], dtype='<U21'),
 numpy.ndarray,
 (3, 3))

In [20]:
a

array([['1', 'sai', '10'],
       ['2', 'sia', '20'],
       ['1', 'ias', '30']], dtype='<U21')

In [21]:
a[:]

array([['1', 'sai', '10'],
       ['2', 'sia', '20'],
       ['1', 'ias', '30']], dtype='<U21')

In [24]:
# start to end range `:`
# rows and cols `,`
# cols
a[: , 2]

array(['10', '20', '30'], dtype='<U21')

In [32]:
score = a[:, -1]

In [33]:
# the results `score` is also a numpy array as it is sliced from the numpy array
type(score)

numpy.ndarray

In [35]:
# its a 1d array == vector
score.shape

(3,)

In [37]:
score.mean()
# shows an error, here the datatype is a different `dtype='<U21'`
# numpy array can hold different datatypes in it

TypeError: cannot perform reduce with flexible type

In [38]:
score.dtype

dtype('<U21')

In [44]:
# so we convert the datatype of the score using the `astype()` fucntion
s = score.astype(int)

In [45]:
s.dtype

dtype('int64')

In [43]:
s.mean()

20.0

In [47]:
s.min()

10

In [48]:
s.max()

30

In [62]:
a

array([['1', 'sai', '10'],
       ['2', 'sia', '20'],
       ['3', 'ias', '30']], dtype='<U21')

In [59]:
# in numpy we can provide the field name, it supports (in market people believe it cant so we move to pandas)
# example to demonstrate the field name in numpy
# a had no field names
a.dtype

dtype('<U21')

In [57]:
c = numpy.array([1, 2, 3])
c.dtype

dtype('int64')

In [58]:
d = numpy.array(["1", "2", "3"])
d.dtype

dtype('<U1')

In [67]:
# if you observe the dtypes of a ('<U21'), c('int64') and d ('<U1') are different at a: we have mixture of numericals and strings, c: its only numericals and d: has only strings. The dtype values for different mixture and individual datatypes is different.
# inorder to provide the filed names, we need to update it

a.dtype = {'names' : ['StudentRollNo', 'StudentName', 'StudetnAttendance'], 'formats' : [numpy.int64, numpy.unicode, numpy.int64]}
a

ValueError: When changing to a smaller dtype, its size must be a divisor of the size of original dtype

In [68]:
t = numpy.array([1, 2, 3])
t

array([1, 2, 3])

In [69]:
t.dtype

dtype('int64')

In [70]:
t.dtype = {'names' : ['ID'], 'formats' : [numpy.int64]}

In [71]:
t

array([(1,), (2,), (3,)], dtype=[('ID', '<i8')])

In [72]:
t['ID']

array([1, 2, 3])

In [73]:
import pandas

In [74]:
# pandas.read_csv 